// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKsCZwhB_nmeBEcOclvHgR5D1yQsOrNw',
    appId: '1:1059870775160:web:15531b645b0109838a9a8d',
    messagingSenderId: '1059870775160',
    projectId: 'wikato-3ce27',
    authDomain: 'wikato-3ce27.firebaseapp.com',
    storageBucket: 'wikato-3ce27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYZVRphvOnLmjbYY1CgHFHJoLLQOwO_k',
    appId: '1:1059870775160:android:d0a2ecca6ca8fc848a9a8d',
    messagingSenderId: '1059870775160',
    projectId: 'wikato-3ce27',
    storageBucket: 'wikato-3ce27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPdm5tmurbe3O0wA7w5tLX5hU1AxkMik8',
    appId: '1:1059870775160:ios:5eac0ade30c11fb68a9a8d',
    messagingSenderId: '1059870775160',
    projectId: 'wikato-3ce27',
    storageBucket: 'wikato-3ce27.firebasestorage.app',
    iosBundleId: 'com.example.wikato',
  );
}
